repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: forbid-tabs
        exclude: ^.*\.(go|mod)$
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.36.2
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.10.1
    hooks:
      - id: golangci-lint
        args: ["--timeout=5m"]
      - id: golangci-lint-fmt
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.4
    hooks:
    -   id: go-mod-tidy
