//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppRoleAuthRef) DeepCopyInto(out *AppRoleAuthRef) {
	*out = *in
	out.RoleIdSecretRef = in.RoleIdSecretRef
	out.SecretIdSecretRef = in.SecretIdSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppRoleAuthRef.
func (in *AppRoleAuthRef) DeepCopy() *AppRoleAuthRef {
	if in == nil {
		return nil
	}
	out := new(AppRoleAuthRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCredentialsSecretRef) DeepCopyInto(out *ClusterCredentialsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCredentialsSecretRef.
func (in *ClusterCredentialsSecretRef) DeepCopy() *ClusterCredentialsSecretRef {
	if in == nil {
		return nil
	}
	out := new(ClusterCredentialsSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesSecretEngineSpec) DeepCopyInto(out *KubernetesSecretEngineSpec) {
	*out = *in
	if in.ClusterCredentialsSecretRef != nil {
		in, out := &in.ClusterCredentialsSecretRef, &out.ClusterCredentialsSecretRef
		*out = new(ClusterCredentialsSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesSecretEngineSpec.
func (in *KubernetesSecretEngineSpec) DeepCopy() *KubernetesSecretEngineSpec {
	if in == nil {
		return nil
	}
	out := new(KubernetesSecretEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthSpec) DeepCopyInto(out *VaultAuthSpec) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.AppRoleAuthRef != nil {
		in, out := &in.AppRoleAuthRef, &out.AppRoleAuthRef
		*out = new(AppRoleAuthRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthSpec.
func (in *VaultAuthSpec) DeepCopy() *VaultAuthSpec {
	if in == nil {
		return nil
	}
	out := new(VaultAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultK8sConfig) DeepCopyInto(out *VaultK8sConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultK8sConfig.
func (in *VaultK8sConfig) DeepCopy() *VaultK8sConfig {
	if in == nil {
		return nil
	}
	out := new(VaultK8sConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultK8sConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultK8sConfigList) DeepCopyInto(out *VaultK8sConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultK8sConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultK8sConfigList.
func (in *VaultK8sConfigList) DeepCopy() *VaultK8sConfigList {
	if in == nil {
		return nil
	}
	out := new(VaultK8sConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultK8sConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultK8sConfigSpec) DeepCopyInto(out *VaultK8sConfigSpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	in.Engine.DeepCopyInto(&out.Engine)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultK8sConfigSpec.
func (in *VaultK8sConfigSpec) DeepCopy() *VaultK8sConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VaultK8sConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultK8sConfigStatus) DeepCopyInto(out *VaultK8sConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultK8sConfigStatus.
func (in *VaultK8sConfigStatus) DeepCopy() *VaultK8sConfigStatus {
	if in == nil {
		return nil
	}
	out := new(VaultK8sConfigStatus)
	in.DeepCopyInto(out)
	return out
}
