apiVersion: environments.arc.ucl/v1
kind: VaultK8sConfig
metadata:
  labels:
    app.kubernetes.io/name: vault-k8s-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: vaultk8sconfig-sample
spec:
  vaultAddress: https://vault.example.com
  auth:
    tokenSecretRef:
      name: vault-auth
      key: token
  engine:
    mountPath: kubernetes
    kubernetesHost: https://kubernetes.default.svc
    clusterCredentialsSecretRef:
      name: kube-cluster-credentials
      namespace: vault-k8s-config-operator-system
      jwtKey: token
      caCertKey: ca.crt
