---
name: Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Cache prek
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: ~/.cache/prek
        key: cache-${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Set up uv
      uses: astral-sh/setup-uv@06e4edb239928eb926db9fa84abd11632bf44baa # v7
      with:
        activate-environment: true
        python-version: 3.14

    - name: Set up Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
      with:
        go-version: 1.25

    - name: Install prek
      shell: bash
      run: uv pip install prek

    - name: Run prek
      shell: bash
      run: uv run prek run --all-files --color always --verbose
